### ISSUE TITLE
/ctf stone doesn't consume reinforcement material | Dupe

### ISSUE THREAD

**Issue by drjawa** [Civcraft/Citadel#99]
When using /ctf for stone protection and placing stone, it doesn't use up 2 stone, it only uses the one placed. Then when broken it give back the cobble and 1 stone.

**Comment by ttk2** [comment]
oh that's a spigot bug.

**Comment by PromoFaux** [comment]
Just a silly thought, could this be leveraged as a "feature" rather than a bug?

How much of an impact on performance does a cobble generator have? (i.e cobble created from lava and water touching)

With this,You could have a bot /ctf some stone down, and then /ctb, collect the cobble, and then repeat. Would that improve things, or would it be negligible?

It's also open to abuse I guess, if you /ctb it with a ST pick, you'll get back 2 stone (for the cost of 1) BUT it would be much easier to use a stone factory...

**Comment by ttk2** [comment]
cobble generators are not really a big deal, I would really prefer to just keep the flow of Citadel unchanged.

**Comment by Scuwr** [comment]
I've been going through the old issues logs. I think this one needs to be closed. Any advice on where I should direct my attention?

**Comment by Maxopoly** [comment]
Was this ever confirmed fixed?

**Comment by Maxopoly** [comment]
@Scuwr You could add an option to CombatTagPlus to display who was attacking in a tag mesage, instead of just showing the same message to both,, that has been requested often.

We don't have our own CTP version, it's actual repo is here: https://github.com/MinelinkNetwork/CombatTagPlus

Make a clean and tested PR to that repo and explain your changes, otherwise they wont merge it.

**Comment by ProgrammerDan** [comment]
This fix is fixed, ya

**Comment by Scuwr** [comment]
@Maxopoly My most recent merge should have fixed both issues with /ctr and /ctf

**Comment by Maxopoly** [comment]
Or if you want something else you could fix BetterShards randomspawning.

https://github.com/Civcraft/BetterShards/blob/master/src/vg/civcraft/mc/bettershards/misc/RandomSpawn.java

It's currently deactivated, the big issue with it was that if we listen for the respawn event and then send the player to another sharding during the event, he will be serialized while he is still dead and when he pressed respawn on the other shard, he gets teleported again, endless cycle. It needs some workaround, either Mercury magic or delay the teleport without having the player respawn in the world he is in.


Also the general code to pick a spawn location could be improved

**Comment by Maxopoly** [comment]
Or you could do one of those:

https://github.com/Civcraft/NameLayer/issues/158

https://github.com/Civcraft/ItemExchange/issues/20
